---
- name: Add application user
  user:
    name: app
    create_home: false
    home: "/var/lib"

- name: Add application binaries
  copy:
    src: "../../{{ item }}"
    dest: "/usr/local/bin/"
    owner: app
    group: app
    mode: "0755"
  with_items: "{{ app_binaries }}"

- name: Add systemd service files for application
  template:
    src: "application.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ app_binaries }}"

- name: Start and enable application services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ app_binaries }}"
